Uprev to GHC 8.10.7
OpenXT/manager pull request #207
Opened 2023-04-26 18:16 UTC by crogers1

Refer to individual commits for more details. The primary PR can be found against xenclient-oe here:

https://github.com/OpenXT/xenclient-oe/pull/1469

2023-04-28 13:36 UTC, crogers1 commented
There was something strange with the commit history, I rebased on master and pushed to my branch.  Looks better now.

2023-05-01 17:04 UTC, jandryuk requested changes
Looks good.  Can the whitespace cleanup in https://github.com/OpenXT/manager/pull/207/commits/bd449d5ee4f7a101c0756c2370797b22f156f9cf just be folded into the ealier commits, please?

2023-05-03 16:09 UTC, crogers1 commented on updatemgr/Db.hs
> +--    fmap = ap . return
They can be deleted. oversight during cleanup.

2023-05-03 16:16 UTC, crogers1 commented on rpc-proxy/Msg/JsonConv.hs
> +      <*> pure (parseBusName $ jreqDest r)
Split this change out specifically and put it into the "Update conversion methods" commit, which has a new sha after the rebase and push [1a82888](https://github.com/OpenXT/manager/pull/207/commits/1a828883ac2597ac6bf4a063f0d9d5d812c3bd47).

2023-05-03 16:19 UTC, crogers1 commented on rpc-proxy/Msg/JsonConv.hs
> +    maybeParseString parserObjectPathInternal s
The "Internal" forward ports have been removed completely.

2023-05-03 17:02 UTC, crogers1 commented on rpc-proxy/Msg/JsonConv.hs
> +    maybeParseString parserObjectPathInternal s
Removed the removal commit, and just dropped all the Internal forward port stuff in the commit that originally introduced it.

2023-05-03 17:04 UTC, crogers1 commented
Was able to consolidate a few more commits.  Took the Setup.hs changes and put them all into a single commit, no need for the intermediate change to Setup.hs.in since we just want the symlinks back to Setup.hs.  Also squashed the single line change to the `inparams` for Msg/Json.hs that was it's own commit and put that into the larger commit for that module [a9a1bb6](https://github.com/OpenXT/manager/pull/207/commits/a9a1bb69ac54c5e60ce84d3ee825d0ffc732a18e)

2023-05-03 18:11 UTC, crogers1 commented
Yea absolutely.

2023-05-04 12:15 UTC, jandryuk approved these changes
Thanks!

2023-11-16 14:26 UTC, jandryuk commented
build failure:
| 
| XenMgr/Host.hs:816:13: error:
|     • Variable not in scope: catch :: IO String -> (p0 -> m0 a1) -> t
|     • Perhaps you meant one of these:
|         ‘E.catch’ (imported from Control.Exception),
|         ‘match’ (imported from Text.Regex.Posix)
|     |
| 816 |   pcmDevs = catch ( readFile "/proc/asound/pcm" )
|     |    

From after the audio changes, I guess

2023-11-16 15:10 UTC, jandryuk commented
Tabs slipped into:
xenmgr/Vm/Config.hs (sorry about that)
xenmgr/Vm/PciDatabase.hs

Fixup in https://github.com/OpenXT/manager/pull/207/commits/2e257d980b05c0183ca24055f3122ec0a930eb76 please

There is another catch error in XenMgr/Expose/HostObject.hs:402:11

2023-11-17 16:13 UTC, crogers1 commented
Fixed the tab in Config, don't see any tabs in PciDatabase that aren't commented out.  Did not observe any build errors in HostObject.hs

2023-11-17 16:24 UTC, jandryuk commented
Oh, I didn't realize PciDatabase's hard tabs were commented out - I just saw them in the grep output.

Thanks for the fixup.

Did you build this branch in isolation or merged into master?  I think the compile errors only show up with it merged into master.

2023-11-17 16:44 UTC, crogers1 commented
it was in isolation, I'll have to rebase it on master

2023-12-18 20:07 UTC, merged